apiVersion: apps/v1
kind: Deployment
metadata:
  name: devlens-frontend
  namespace: devlens
  labels:
    app: devlens-frontend

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: devlens-frontend

  template:
    metadata:
      labels:
        app: devlens-frontend

    spec:
      containers:
      - name: devlens-frontend

        image: radhiraj23/devlens-frontend-beta:4cabb1c

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "250m"
            memory: "256Mi"

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 20

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10