apiVersion: v1
kind: Service
metadata:
  name: devlens-service
  namespace: devlens

spec:
  selector:
    app: devlens-frontend

  type: LoadBalancer

  ports:
  - port: 80
    targetPort: 80
    protocol: TCP