apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: devlens
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/dhiraj639/Devlens-Gitops-pipeline.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: devlens

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true